### PR TITLE
Use quay.io registry

### PR DESCRIPTION
**Pull request by arajkumar**

### CODE REVIEW

**Review by miteshvp — APPROVED** [review]
LGTM. Thanks.

**Comment by miteshvp** [comment]
@arajkumar - you need to make sure those QUAY creds are part of env. That is why it is failing to push to quay.io

**Comment by arajkumar** [comment]
[check]

**Comment by arajkumar** [comment]
@miteshvp, check was failing due to missing repo `quay.io/openshiftio/fabric8-analytics-api-gateway`. It got fixed now.

**Pull request merged**
